name: ci

on:
  pull_request:
    branches:
      - newsite

  push:
    branches:
      - newsite

jobs:
  test:
    name: Test run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@master
      - name: run test
        env:
          REF: ${{ github.ref}}
        run: |
          echo Checking github env variables:
          echo ${{ github.actor }}
          echo ${{ github.event_name }}
          echo ${{ github.sha }}
          echo ${REF}
          IFS='/' read -r -a array <<< "$REF";
          echo PR number is :
          echo "${array[2]}";
  deploy:
    name: Deploy on surge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10
        python-version:
          - 3.7
    steps:
      - uses: actions/checkout@master
      - name: deploy in surge
        uses: ./.github/actions/deploy-action
        id: deploy
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN}}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN}}
          REF: ${{ github.ref}}
      - name: Get the output time
        run: echo "The output was ${{ steps.deploy.outputs.deployed-domain }}"
